site_name: Hivemind
repo_url: https://github.com/ProjectHivemind
repo_name: ProjectHivemind
edit_uri: ""

nav:
  - Home: index.md
  - Framework: '!include ./framework/mkdocs.yml'
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    scheme: preference
  features:
    - navigation.tabs
    
plugins:
  - monorepo
  - search:
      prebuild_index: true
      lang: en
