# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        
      - name: Check out my other repo
        uses: actions/checkout@master
        with:
          repository: ProjectHivemind/ImplantFramework
          path: ImplantFramework 

      - name: Install doxygen
        run: sudo apt-get install doxygen 
      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build
      
      - name: Get Doxybook2 and add to path
        working-directory: ${{github.workspace}}
        shell: bash
        run: sh ./getDoxybook2.sh; sudo mv ./doxybook2/bin/doxybook2 /usr/bin/; sudo chmod +x /usr/bin/doxybook2

      - name: Configure CMake for Framework
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE/ImplantFramework

      - name: Build Framework docs
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: make Doxybook2

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ls -la; ls -la ./docs/out
